### ISSUE TITLE
stray line break

### ISSUE THREAD

**Issue by phil-ho** [KFCNuggets/project-catwalk#41]
https://github.com/KFCNuggets/project-catwalk/blob/390e195c1adab17ecdb52b9215ac5e173c10e5e6/client/src/components/RatingsAndReviews/ReviewList.jsx#L100

probably could be done better with styling elsewhere

**Comment by stl026** [comment]
I removed the line break and it was perfectly fine. I most likely put it in the very beginning as some janky way to fix something.
