### ISSUE TITLE
multiple renders

### ISSUE THREAD

**Issue by phil-ho** [KFCNuggets/project-catwalk#45]
https://github.com/KFCNuggets/project-catwalk/blob/390e195c1adab17ecdb52b9215ac5e173c10e5e6/client/src/components/App.jsx#L21-L55

@stl026 @katehyerinjeon @ChhuongLe 

Each axios request here is async, and whenever they are resolved, will call `setState`. Remember that every call to `setState` will also call `render`. This can lead to more-than-expected re-renders of your component and affect performance.

One of many solutions might be to use `Promise.all` 

PS - React is smart about batching multiple `setState` calls together but because your code here is async, there's no guarantee you'll benefit from this.

**Comment by stl026** [comment]
Your brain is ginormous Phillip. Thank you
