### ISSUE TITLE
DRYing up your code

### ISSUE THREAD

**Issue by phil-ho** [KFCNuggets/project-catwalk#47]
https://github.com/KFCNuggets/project-catwalk/blob/390e195c1adab17ecdb52b9215ac5e173c10e5e6/client/src/components/RelatedItems/CardList.jsx#L76-L144

in general, I like to stay away from having multiple return statements because
1. a lot of times it means you're repeating yourself.
2. it causes your code to be a lot longer than necessary
3. changes to common code will have to be applied in multiple places

Notice how inside each of your return statements, the Title, Wrapper, and Card components stay the same. That means we only have to conditionally render the Arrows. We can even abstract out the mapping of the Cards to make it even cleaner for readability purposes.

```js
let leftArrow; // defaults to undefined
let rightArrow;

if (shouldShowLeftArrow) {
  leftArrow = (<Arrow className="left" onClick={moveLeft} />);
} 

if (shouldShowRightArrow) {
  rightArrow =  (<Arrow data-testid="rightArrow" className="right" onClick={moveRight} />);
}

let cardComponents = cards.map((...) => {
... });

return (
  <>
  <Title>Related Products!</Title>
      <Wrapper>
        {leftArrow} // if its still undefined, nothing will render in its place
        {cardComponents}
        {rightArrow}
      </Wrapper>
  </>
);
```

**Comment by ChhuongLe** [comment]
Thanks Phillip! This will make reading my code more pleasant even for myself!
